bindPort = 7000

auth.method = "token"
auth.token = "FRP_TOKEN"

allowPorts = [
  { start = 14000, end = 15000 }
]
maxPortsPerClient = 1

log.to = "./frps.log"
log.level = "info"
log.maxDays = 3

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "USER"
webServer.password = "PASSWORD"

[[httpPlugins]]
name = "rate-limit-enforcer"
addr = "127.0.0.1:9002"
path = "/handler"
ops = ["NewProxy"]
